/*
ATLIQ TECHNOLOGY - SUPPLY CHAIN FINANCE MANAGEMENT
================================================================================
Database: SupplyChainFinanceManagement
Tool: Microsoft SQL Server
================================================================================
Introduction : 
AtliQ Technology, established in 2018, operates in the hardware manufacturing sector, specializing in electronic gadgets like mice, keyboards, laptops, printers, etc. 
The company distributes its products to a diverse range of customers, including both both Brick&Motar and Online stores. These intermediary customers subsequently sell 
the products to end-users.

AtliQ have a manufacturing facility where they build all this hardware and then they send it to a warehouse, distribution centers and so on they have business in 
different countries, so they ship or supply these hardware gadgets to different customers across different countries. AtliQ diversifies its sales channels, employing 
both brick-andmortar stores and online E-commerce marketplaces to get their 
products into customers’ hands. 

In terms of customer channels, they utilize 3 types of Channels in selling their products to consumers : 
1. Retailers :- This includes partnerships with both traditional brick-and- mortar stores and online marketplaces. 
2. Direct Sales :- They also operate their own online stores (AtliQ Direct E-Stores) and physical exclusive showrooms (AtliQ Exclusive showrooms). 
3. Distributors :- They leverage a network of distributors to distribute product to local stores across the country.

Next up: AtliQ Hardware’s financial breakdown. Let’s figure out how AtliQ Hardware makes money! 
Here’s an illustrative example :- 
AtliQ sells a mouse to Croma for $30 gross price. That is the base price that AtliQ has set for this particular Mouse. Now there is some amount that needs to be deducted from this 
30$ because AtliQ sets a base gross price of $30 for a mouse sold to Croma. This is the full price, but Croma gets a special discount at the start of each year based on thier longstanding 
business relationship and the sales volume generated by the croma store for AtliQ. This pre-negotiated annual discount made at the beginning of each year is called as Pre-Invoice Deductions. 
Let’s assume the agreed discount for this mouse is $2, although it’s typically expressed as a percentage. Therefore, when AtliQ sells this mouse, Croma pays $28 instead of $30 after the deduction. 
This $28 is nothing but the Net Invoice Sales. 

After this process, Croma provides promotional offers to customers, facilitated by AtliQ Hardware. For instance, during festive seasons like Christmas or Diwali, AtliQ Hardware might suggest a 5% 
discount for the entire month as a promotional offer that Croma can extend to its consumers. So that is promotional offer. Discounts aren’t the only way AtliQ pushes their products. AtliQ wants 
their products to stand out, so they sometimes offer stores like Croma this premium discount or a bonus, called a “placement fees”, to put them at a prime location in the stores, hoping that this 
will draw more attention and boost their sales. This is a strategy to boost sales for AtliQ Hardware, especially considering that Croma may also source hardware from other manufacturers like Dell 
and HP. It’s all about getting their products noticed and bought! This is another way for them to compete with bigger brands and get their products noticed. Let’s say chroma is pretty good in selling 
these devices. They generate lot of sales for AliQ Hardware. So besides discounts like a base price discount, placement fees for prime locations, AtliQ can offer or rewards croma with other incentives 
or a bonus, called a “performance rebate” if the store sells a lot of their products. Basically, the more devices Croma sells, the more money they get back from AtliQ at the end of the quarter or a 
month or a year, which benefits both companies in the long run. It’s like a way of saying “Thank you for being a great sales partner! We appreciate your business!” After the initial pre-invoice sales 
price is set, there are 3 types of discounts AtliQ can use to further reduce the cost for stores like Croma. 

These 3 types of discounts that we discussed earlier come under the Post-invoice Deductions. Think of post-invoice deductions as adjustments made after the initial sale of a product. 
Post-invoice Deductions = festival sales discount or promotional offer discount from the consumer (i.e shoppers) + Platform fee from croma (i.e AtliQ’s customer) + Performance Rebates based on how well 
                          croma sell (i.e AtliQ’s customer). 
After AtliQ sells a mouse to Croma, there might be some savings and adjustments to the final price. We call these adjustments “Post-invoice deductions”. All these “Post-invoice deductions” add up to more 
profit for Croma on each AtliQ device they sell, further reducing the cost, creating a flexible pricing system! These adjustments can significantly lower the final cost for croma stores and hence AtliQ 
easily builds loyalty with stores like Croma through post-invoice adjustments. So, AtliQ sold mouse to croma for 28$ before Post-invoice deductions. At the end of the selling period (month or quarter or Year), 
they decide and come to agreement for Post-invoice deductions which amount to $3. We need to account for those Post-invoice deductions (discounts, fees and rebates) to get the Net Sales. To figure out Net 
Sales, we must deduct the Post-invoice deduction amount from the initial invoiced amount (Net Invoice 
Sales) paid by Croma. 
Net Sales actually defines the price of the product after considering all the deductions. 
Net Sales = Gross Price — (Pre-invoice deduction + Postinvoice deduction) 
Net Sales = (Gross Price — Pre-invoice deduction) — Postinvoice deduction 
Net Sales = Net invoice Sales — Post-invoice deduction 

So eventually at the end of the day AliQ is selling mouse to croma for $25, which is the revenue of AtliQ Hardware Technologies (Net Sales). After we cut those extra discounts from the initial invoiced 
amount (Net Invoice Sales) we get Net Sales amount. We now need to deduct the cost of goods sold(COGS) which includes the sum of : 
1. Manufacturing Cost 
2. Freight Cost (Transportation) 
3. Other expenses & costs 
from the Net Sales to get our gross profit. 
This tells us how much money we actually earned from selling the mouse to Croma. 

Suppose the COGS amount for this mouse is $20. After deducting the COGS amount from Net sales we get profit. $20 COGS means AtliQ Hardware earns a profit of $5 per mouse. 
That’s $5 for each mouse. This profit is also referred to as Gross Margin or Gross Margin on Net Sales. 
Gross Margin = Net Sales — Cost of Goods sold (COGS) 
Gross Margin as % of Net Sales = Gross Margin / Net Sales 
Hence Gross Margin comes out as 20% of Net Sales That means AtliQ Hardware make 20% profit on every mouse they sell ($5 profit divided by the $25 sale price), after accounting for the cost of making and shipping them. 
This is a quick summary of Profit and Loss statement. This summary is about the business model of the AtliQ, now we can move towards the tables. 

AtliQ Technology initiates its business/financial year in September in the month of September by every year, aligning with high sales and the festive season lasting from September 
to December. This fiscal year runs from September to August. All analyses conducted will be based on that particular fiscal year timeframe, ensuring consistency and relevance. 
*/

-- TASK 1
-- ====================================================================================================================================================================================================================================
-- Q1) Create a database named as SupplyChainFinanceManagement

USE master;
IF DB_ID(N'SupplyChainFinanceManagement') IS NOT NULL
BEGIN
    ALTER DATABASE SupplyChainFinanceManagement SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SupplyChainFinanceManagement;
END;

CREATE DATABASE SupplyChainFinanceManagement;
USE SupplyChainFinanceManagement;

-- Q2) Create nine tables with the columns given in the project.
CREATE TABLE dim_customer (
    customer_code BIGINT PRIMARY KEY,
    customer VARCHAR(50) NOT NULL,
    platform VARCHAR(45),
    channel VARCHAR(45),
    market VARCHAR(45),
    sub_zone VARCHAR(45),
    region VARCHAR(45)
);
CREATE TABLE dim_product (
    product_code VARCHAR(45) PRIMARY KEY,
    division VARCHAR(45),
    segment VARCHAR(45),
    category VARCHAR(45),
    product VARCHAR(200),
    variant VARCHAR(45),
    inventory_count INT NOT NULL DEFAULT 0
);
CREATE TABLE fact_forecast_monthly (
    date DATE NOT NULL,
    fiscal_year INT NOT NULL,
    product_code VARCHAR(45) NOT NULL,
    customer_code BIGINT NOT NULL,
    forecast_quantity INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_fact_forecast_monthly
        PRIMARY KEY (date, product_code, customer_code),
    CONSTRAINT FK_forecast_product
        FOREIGN KEY (product_code) REFERENCES dim_product(product_code),
    CONSTRAINT FK_forecast_customer
        FOREIGN KEY (customer_code) REFERENCES dim_customer(customer_code),
    CONSTRAINT CK_forecast_quantity_nonnegative CHECK (forecast_quantity >= 0)
);

CREATE TABLE fact_freight_cost (
    market VARCHAR(45) NOT NULL,
    fiscal_year INT NOT NULL,
    freight_pct DECIMAL(5,4),
    other_cost_pct DECIMAL(5,4),
    CONSTRAINT PK_fact_freight_cost PRIMARY KEY (market, fiscal_year)
    CONSTRAINT CK_forecast_quantity_nonnegative
        CHECK (forecast_quantity >= 0)
);
CREATE TABLE fact_gross_price (
    product_code VARCHAR(45) NOT NULL,
    fiscal_year INT NOT NULL,
    gross_price DECIMAL(15,4) NOT NULL,
    CONSTRAINT PK_fact_gross_price PRIMARY KEY (product_code, fiscal_year),
    CONSTRAINT FK_gross_price_product FOREIGN KEY (product_code) REFERENCES dim_product(product_code),
    CONSTRAINT CK_gross_price_nonnegative CHECK (gross_price >= 0)
);
CREATE TABLE fact_manufacturing_cost (
    product_code VARCHAR(45) NOT NULL,
    cost_year INT NOT NULL,
    manufacturing_cost DECIMAL(15,4) NOT NULL,
    CONSTRAINT PK_fact_manufacturing_cost
        PRIMARY KEY (product_code, cost_year),
    CONSTRAINT FK_manufacturing_product
        FOREIGN KEY (product_code) REFERENCES dim_product(product_code),
	CONSTRAINT CK_manufacturing_cost_nonnegative
        CHECK (manufacturing_cost >= 0)
);
CREATE TABLE fact_post_invoice_deductions (
    customer_code BIGINT NOT NULL,
    product_code VARCHAR(45) NOT NULL,
    date DATE NOT NULL,
    discounts_pct DECIMAL(5,4),
    other_deductions_pct DECIMAL(5,4),
    CONSTRAINT PK_fact_post_invoice_deductions
        PRIMARY KEY (customer_code, product_code, date),
    CONSTRAINT FK_post_invoice_customer
        FOREIGN KEY (customer_code) REFERENCES dim_customer(customer_code),
    CONSTRAINT FK_post_invoice_product
        FOREIGN KEY (product_code) REFERENCES dim_product(product_code)
);
CREATE TABLE fact_pre_invoice_deductions (
    customer_code BIGINT NOT NULL,
    fiscal_year INT NOT NULL,
    pre_invoice_discount_pct DECIMAL(5,4),
    CONSTRAINT PK_fact_pre_invoice_deductions
        PRIMARY KEY (customer_code, fiscal_year),
    CONSTRAINT FK_pre_invoice_customer
        FOREIGN KEY (customer_code) REFERENCES dim_customer(customer_code)
);
CREATE TABLE fact_sales_monthly (
    date DATE NOT NULL,
    product_code VARCHAR(45) NOT NULL,
    customer_code BIGINT NOT NULL,
    sold_quantity INT NOT NULL,
    CONSTRAINT PK_fact_sales_monthly
        PRIMARY KEY (date, product_code, customer_code),
    CONSTRAINT FK_sales_product
        FOREIGN KEY (product_code) REFERENCES dim_product(product_code),
    CONSTRAINT FK_sales_customer
        FOREIGN KEY (customer_code) REFERENCES dim_customer(customer_code),
    CONSTRAINT CK_sales_quantity_positive CHECK (sold_quantity > 0)
);
-- Supporting table audit_log is also created because Task-5 Q4 requires it.
CREATE TABLE audit_log (
    audit_id INT IDENTITY(1,1) PRIMARY KEY,
    table_name VARCHAR(100) NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    action_date DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    product_code VARCHAR(45),
    customer_code BIGINT,
    sold_quantity INT,
    message VARCHAR(500)
);

-- TASK 2
-- Q1) After creating the tables insert the given records into respective tables.
-- -------------------- dim_customer --------------------
INSERT INTO dim_customer
(customer_code, customer, platform, channel, market, sub_zone, region)
VALUES
(70020104, 'Atliq e Store', 'E-Commerce', 'Direct', 'Austria', 'NE', 'EU'),
(70021096, 'Atliq e Store', 'E-Commerce', 'Direct', 'United Kingdom', 'NE', 'EU'),
(70022084, 'Atliq Exclusive', 'Brick & Mortar', 'Direct', 'USA', 'NA', 'NA'),
(70022085, 'Atliq e Store', 'E-Commerce', 'Direct', 'USA', 'NA', 'NA'),
(70023031, 'Atliq Exclusive', 'Brick & Mortar', 'Direct', 'Canada', 'NA', 'NA'),
(70023032, 'Atliq e Store', 'E-Commerce', 'Direct', 'Canada', 'NA', 'NA'),
(70026206, 'Atliq e Store', 'E-Commerce', 'Direct', 'Mexico', 'LATAM', 'LATAM'),
(70027208, 'Atliq e Store', 'E-Commerce', 'Direct', 'Brazil', 'LATAM', 'LATAM'),
(80001019, 'Neptune', 'Brick & Mortar', 'Distributor', 'China', 'ROA', 'APAC'),
(80006154, 'Synthetic', 'Brick & Mortar', 'Distributor', 'Philiphines', 'ROA', 'APAC'),
(80006155, 'Novus', 'Brick & Mortar', 'Distributor', 'Philiphines', 'ROA', 'APAC');
-- SUPPORT CUSTOMER KEYS REFERENCED BY THE SUPPLIED FACT SAMPLE
INSERT INTO dim_customer
(customer_code, customer, platform, channel, market, sub_zone, region)
VALUES
(70002017, 'Support Customer 70002017', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70002018, 'Support Customer 70002018', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70003181, 'Support Customer 70003181', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70003182, 'Support Customer 70003182', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70006157, 'Support Customer 70006157', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70006158, 'Support Customer 70006158', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70007198, 'Support Customer 70007198', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70007199, 'Support Customer 70007199', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70008169, 'Support Customer 70008169', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70008170, 'Support Customer 70008170', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC'),
(70011193, 'Support Customer 70011193', 'E-Commerce', 'Direct', 'India', 'ROA', 'APAC');
-- -------------------- dim_product --------------------
INSERT INTO dim_product
(product_code, division, segment, category, product, variant)
VALUES
('A1919150403', 'P&A', 'Peripherals', 'MotherBoard', 'AQ MB Lito', 'Plus 2'),
('A1920150404', 'P&A', 'Peripherals', 'MotherBoard', 'AQ MB Lito', 'Premium'),
('A2020150501', 'P&A', 'Peripherals', 'MotherBoard', 'AQ MB Lito 2', 'Standard'),
('A2020150502', 'P&A', 'Peripherals', 'MotherBoard', 'AQ MB Lito 2', 'Plus 1'),
('A2021150503', 'P&A', 'Peripherals', 'MotherBoard', 'AQ MB Lito 2', 'Plus 2'),
('A2021150504', 'P&A', 'Peripherals', 'MotherBoard', 'AQ MB Lito 2', 'Premium'),
('A2118150101', 'P&A', 'Accessories', 'Mouse', 'AQ Master wired x1 Ms', 'Standard 1'),
('A2118150102', 'P&A', 'Accessories', 'Mouse', 'AQ Master wired x1 Ms', 'Standard 2'),
('A2118150103', 'P&A', 'Accessories', 'Mouse', 'AQ Master wired x1 Ms', 'Plus 1'),
('A2118150104', 'P&A', 'Accessories', 'Mouse', 'AQ Master wired x1 Ms', 'Plus 2'),
('A2118150105', 'P&A', 'Accessories', 'Mouse', 'AQ Master wired x1 Ms', 'Premium 1');
-- SUPPORT PRODUCT KEYS REFERENCED BY THE SUPPLIED FACT SAMPLE
INSERT INTO dim_product
(product_code, division, segment, category, product, variant, inventory_count)
VALUES
('A0118150101', 'P&A', 'Accessories', 'Mouse',
 'Support Product A0118150101', 'Support Variant 1', 1000),
('A0118150102', 'P&A', 'Accessories', 'Mouse',
 'Support Product A0118150102', 'Support Variant 2', 1000),
('A0118150103', 'P&A', 'Accessories', 'Mouse',
 'Support Product A0118150103', 'Support Variant 3', 1000);
 -- -------------------- fact_forecast_monthly --------------------
INSERT INTO fact_forecast_monthly
(date, fiscal_year, product_code, customer_code, forecast_quantity)
VALUES
('2017-09-01', 2018, 'A0118150101', 70002017, 18),
('2017-09-01', 2018, 'A0118150101', 70002018, 11),
('2017-09-01', 2018, 'A0118150101', 70003181, 9),
('2017-09-01', 2018, 'A0118150101', 70003182, 6),
('2017-09-01', 2018, 'A0118150101', 70006157, 5),
('2017-09-01', 2018, 'A0118150101', 70006158, 6),
('2017-09-01', 2018, 'A0118150101', 70007198, 4),
('2017-09-01', 2018, 'A0118150101', 70007199, 7),
('2017-09-01', 2018, 'A0118150101', 70008169, 2),
('2017-09-01', 2018, 'A0118150101', 70008170, 8),
('2017-09-01', 2018, 'A0118150101', 70011193, 5);
-- -------------------- fact_freight_cost --------------------
INSERT INTO fact_freight_cost
(market, fiscal_year, freight_pct, other_cost_pct)
VALUES
('Germany', 2020, 0.0226, 0.0060),
('Germany', 2021, 0.0226, 0.0060),
('Germany', 2022, 0.0226, 0.0060),
('India', 2018, 0.0244, 0.0026),
('India', 2019, 0.0219, 0.0057),
('India', 2020, 0.0309, 0.0029),
('India', 2021, 0.0309, 0.0029),
('India', 2022, 0.0309, 0.0029),
('Indonesia', 2018, 0.0190, 0.0042),
('Indonesia', 2019, 0.0187, 0.0052),
('Indonesia', 2020, 0.0195, 0.0023);
-- -------------------- fact_gross_price --------------------
INSERT INTO fact_gross_price
(product_code, fiscal_year, gross_price)
VALUES
('A0118150101', 2018, 15.3952),
('A0118150101', 2019, 14.4392),
('A0118150101', 2020, 16.2323),
('A0118150101', 2021, 19.0573),
('A0118150102', 2018, 19.5875),
('A0118150102', 2019, 18.5595),
('A0118150102', 2020, 19.8577),
('A0118150102', 2021, 21.4565),
('A0118150103', 2018, 19.3630),
('A0118150103', 2019, 19.3442),
('A0118150103', 2020, 22.1317);
-- -------------------- fact_manufacturing_cost --------------------
INSERT INTO fact_manufacturing_cost
(product_code, cost_year, manufacturing_cost)
VALUES
('A0118150101', 2018, 4.6190),
('A0118150101', 2019, 4.2033),
('A0118150101', 2020, 5.0207),
('A0118150101', 2021, 5.5172),
('A0118150102', 2018, 5.6036),
('A0118150102', 2019, 5.3235),
('A0118150102', 2020, 5.7180),
('A0118150102', 2021, 6.2835),
('A0118150103', 2018, 5.9469),
('A0118150103', 2019, 5.5306),
('A0118150103', 2020, 6.3264);
-- -------------------- fact_post_invoice_deductions --------------------
INSERT INTO fact_post_invoice_deductions
(customer_code, product_code, date, discounts_pct, other_deductions_pct)
VALUES
(70002017, 'A0118150101', '2017-09-01', 0.2660, 0.0719),
(70002017, 'A0118150101', '2017-10-01', 0.3090, 0.0976),
(70002017, 'A0118150101', '2017-11-01', 0.3313, 0.0752),
(70002017, 'A0118150101', '2018-01-01', 0.2958, 0.0720),
(70002017, 'A0118150101', '2018-02-01', 0.3208, 0.0793),
(70002017, 'A0118150101', '2018-03-01', 0.2635, 0.1007),
(70002017, 'A0118150101', '2018-05-01', 0.2231, 0.0820),
(70002017, 'A0118150101', '2018-06-01', 0.3020, 0.0791),
(70002017, 'A0118150101', '2018-07-01', 0.3123, 0.0929),
(70002017, 'A0118150101', '2018-09-01', 0.1530, 0.1288),
(70002017, 'A0118150101', '2018-10-01', 0.1363, 0.1542);
-- -------------------- fact_pre_invoice_deductions --------------------
INSERT INTO fact_pre_invoice_deductions
(customer_code, fiscal_year, pre_invoice_discount_pct)
VALUES
(70002017, 2018, 0.0824),
(70002017, 2019, 0.0777),
(70002017, 2020, 0.0735),
(70002017, 2021, 0.0703),
(70002017, 2022, 0.1057),
(70002018, 2018, 0.2956),
(70002018, 2019, 0.2577),
(70002018, 2020, 0.2255),
(70002018, 2021, 0.2061),
(70002018, 2022, 0.2931),
(70003181, 2018, 0.0536);
-- -------------------- fact_sales_monthly --------------------
INSERT INTO fact_sales_monthly
(date, product_code, customer_code, sold_quantity)
VALUES
('2017-09-01', 'A0118150101', 70002017, 51),
('2017-09-01', 'A0118150101', 70002018, 77),
('2017-09-01', 'A0118150101', 70003181, 17),
('2017-09-01', 'A0118150101', 70003182, 6),
('2017-09-01', 'A0118150101', 70006157, 5),
('2017-09-01', 'A0118150101', 70006158, 7),
('2017-09-01', 'A0118150101', 70007198, 29),
('2017-09-01', 'A0118150101', 70007199, 34),
('2017-09-01', 'A0118150101', 70008169, 22),
('2017-09-01', 'A0118150101', 70008170, 5),
('2017-09-01', 'A0118150101', 70011193, 10);
-- HELPER FUNCTION
-- Fiscal year starts in September and ends in August.
-- ============================================================================
CREATE FUNCTION dbo.fn_GetFiscalYear (@calendar_date DATE)
RETURNS INT
AS
BEGIN
    RETURN CASE
             WHEN MONTH(@calendar_date) >= 9 THEN YEAR(@calendar_date) + 1
             ELSE YEAR(@calendar_date)
           END;
END;

-- ============================================================================
-- TASK 3
-- ============================================================================

-- Q1) Assume calendar_date is '2023-07-15'. Apply the function to this date
-- and explain what value it will return as the fiscal year.
SELECT '2023-07-15' AS calendar_date, dbo.fn_GetFiscalYear('2023-07-15') AS fiscal_year;
-- Answer: 2023, because July falls before September.

-- Q2) Monthly product transaction / gross-sales report
DECLARE @CustomerCode BIGINT = 70002017;
DECLARE @FiscalYear INT = 2018;

SELECT s.date, s.product_code, p.product, p.variant, s.sold_quantity, gp.gross_price, s.sold_quantity * gp.gross_price AS gross_price_total FROM fact_sales_monthly s
INNER JOIN dim_product p
    ON s.product_code = p.product_code
INNER JOIN fact_gross_price gp
    ON s.product_code = gp.product_code
   AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
WHERE s.customer_code = @CustomerCode
  AND dbo.fn_GetFiscalYear(s.date) = @FiscalYear
ORDER BY s.date, s.product_code;

-- ============================================================================
-- TASK 4 - ANALYTICAL QUESTIONS
-- ============================================================================

-- Q1) Sales Trend Analysis
SELECT
    s.product_code,
    s.date,
    SUM(s.sold_quantity) AS monthly_sales_quantity
FROM fact_sales_monthly s
GROUP BY s.product_code, s.date
ORDER BY s.product_code, s.date;
-- Q2) Customer Segmentation
WITH CustomerSales AS
(
    SELECT
        c.customer_code,
        c.customer,
        c.channel,
        c.market,
        c.region,
        SUM(s.sold_quantity) AS total_quantity,
        COUNT(DISTINCT s.date) AS purchase_months,
        SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS gross_revenue
    FROM dim_customer c
    LEFT JOIN fact_sales_monthly s
        ON c.customer_code = s.customer_code
    LEFT JOIN fact_gross_price gp
        ON s.product_code = gp.product_code
       AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
    GROUP BY c.customer_code, c.customer, c.channel, c.market, c.region
)
SELECT *,
       CASE
         WHEN total_quantity >= 1000 THEN 'High Value'
         WHEN total_quantity >= 500 THEN 'Medium Value'
         ELSE 'Low Value'
       END AS customer_segment
FROM CustomerSales
ORDER BY gross_revenue DESC;
-- Q3) Product Performance Comparison
SELECT
    p.product_code,
    p.product,
    p.variant,
    SUM(s.sold_quantity) AS total_sales_quantity,
    SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS gross_revenue,
    RANK() OVER
      (ORDER BY SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) DESC) AS revenue_rank
FROM dim_product p
LEFT JOIN fact_sales_monthly s
    ON p.product_code = s.product_code
LEFT JOIN fact_gross_price gp
    ON s.product_code = gp.product_code
   AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
GROUP BY p.product_code, p.product, p.variant
ORDER BY revenue_rank;
-- Q4) Market Expansion Opportunities
SELECT
    c.market,
    f.fiscal_year,
    SUM(f.forecast_quantity) AS forecasted_demand
FROM fact_forecast_monthly f
JOIN dim_customer c
  ON f.customer_code = c.customer_code
GROUP BY c.market, f.fiscal_year
ORDER BY forecasted_demand DESC;
-- Q5) Cost Analysis
SELECT
    p.product_code,
    p.product,
    mc.cost_year,
    mc.manufacturing_cost,
    gp.gross_price,
    gp.gross_price - mc.manufacturing_cost AS gross_profit_per_unit,
    CASE
      WHEN gp.gross_price > 0
      THEN ((gp.gross_price - mc.manufacturing_cost) / gp.gross_price) * 100
      ELSE NULL
    END AS profit_margin_pct
FROM dim_product p
JOIN fact_manufacturing_cost mc
  ON p.product_code = mc.product_code
JOIN fact_gross_price gp
  ON mc.product_code = gp.product_code
 AND mc.cost_year = gp.fiscal_year
ORDER BY profit_margin_pct DESC;
-- Q6) Discount Impact Analysis
SELECT
    d.customer_code,
    d.fiscal_year,
    d.pre_invoice_discount_pct,
    SUM(s.sold_quantity * gp.gross_price) AS gross_revenue,
    SUM(s.sold_quantity * gp.gross_price * d.pre_invoice_discount_pct) AS discount_amount,
    SUM(s.sold_quantity * gp.gross_price *
        (1 - d.pre_invoice_discount_pct)) AS net_invoice_revenue
FROM fact_pre_invoice_deductions d
JOIN fact_sales_monthly s
  ON d.customer_code = s.customer_code
 AND d.fiscal_year = dbo.fn_GetFiscalYear(s.date)
JOIN fact_gross_price gp
  ON s.product_code = gp.product_code
 AND d.fiscal_year = gp.fiscal_year
GROUP BY d.customer_code, d.fiscal_year, d.pre_invoice_discount_pct
ORDER BY d.customer_code, d.fiscal_year;
-- Q7) Market-specific Freight Costs
SELECT
    market,
    AVG(freight_pct) AS average_freight_pct,
    AVG(other_cost_pct) AS average_other_cost_pct,
    MIN(freight_pct) AS minimum_freight_pct,
    MAX(freight_pct) AS maximum_freight_pct
FROM fact_freight_cost
GROUP BY market
ORDER BY average_freight_pct DESC;
-- Q8) Seasonal Sales Patterns
SELECT
    dbo.fn_GetFiscalYear(date) AS fiscal_year,
    CASE WHEN MONTH(date) >= 9 THEN MONTH(date) - 8
         ELSE MONTH(date) + 4 END AS fiscal_month_number,
    DATENAME(MONTH, date) AS calendar_month,
    SUM(sold_quantity) AS total_sales_quantity
FROM fact_sales_monthly
GROUP BY
    dbo.fn_GetFiscalYear(date),
    CASE WHEN MONTH(date) >= 9 THEN MONTH(date) - 8
         ELSE MONTH(date) + 4 END,
    DATENAME(MONTH, date)
ORDER BY fiscal_year, fiscal_month_number;
-- Q9) Customer Loyalty Analysis
WITH CustomerMonths AS
(
    SELECT
        customer_code,
        dbo.fn_GetFiscalYear(date) AS fiscal_year,
        COUNT(DISTINCT date) AS active_months
    FROM fact_sales_monthly
    GROUP BY customer_code, dbo.fn_GetFiscalYear(date)
)
SELECT
    customer_code,
    AVG(active_months * 1.0) AS average_active_months,
    COUNT(DISTINCT fiscal_year) AS fiscal_years_with_purchases,
    CASE
      WHEN COUNT(DISTINCT fiscal_year) >= 3 THEN 'High Loyalty'
      WHEN COUNT(DISTINCT fiscal_year) = 2 THEN 'Medium Loyalty'
      ELSE 'Low Loyalty'
    END AS loyalty_segment
FROM CustomerMonths
GROUP BY customer_code
ORDER BY fiscal_years_with_purchases DESC, average_active_months DESC;
-- Q10) Forecast Accuracy Evaluation
SELECT
    f.date,
    f.product_code,
    f.customer_code,
    f.forecast_quantity,
    ISNULL(s.sold_quantity,0) AS actual_sold_quantity,
    CASE
      WHEN f.forecast_quantity = 0 THEN NULL
      ELSE (ISNULL(s.sold_quantity,0) * 100.0 / f.forecast_quantity)
    END AS forecast_accuracy_pct,
    ISNULL(s.sold_quantity,0) - f.forecast_quantity AS variance_quantity
FROM fact_forecast_monthly f
LEFT JOIN fact_sales_monthly s
  ON f.date = s.date
 AND f.product_code = s.product_code
 AND f.customer_code = s.customer_code
ORDER BY f.date, f.product_code, f.customer_code;
-- Q11) Channel Performance Assessment
SELECT
    c.channel,
    SUM(s.sold_quantity) AS total_quantity,
    SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS gross_revenue,
    COUNT(DISTINCT c.customer_code) AS customers
FROM fact_sales_monthly s
JOIN dim_customer c
  ON s.customer_code = c.customer_code
LEFT JOIN fact_gross_price gp
  ON s.product_code = gp.product_code
 AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
GROUP BY c.channel
ORDER BY gross_revenue DESC;
-- Q12) Geographical Sales Distribution
SELECT
    c.region,
    c.market,
    SUM(s.sold_quantity) AS total_sales_quantity,
    SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS gross_revenue
FROM fact_sales_monthly s
JOIN dim_customer c
  ON s.customer_code = c.customer_code
LEFT JOIN fact_gross_price gp
  ON s.product_code = gp.product_code
 AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
GROUP BY c.region, c.market
ORDER BY gross_revenue DESC;
-- Q13) Customer Acquisition Cost Analysis
-- LIMITATION: The supplied schema contains no acquisition-spend field.
SELECT
    'Customer Acquisition Cost cannot be calculated as a true CAC from the supplied nine-table schema because acquisition spend is not provided.'
        AS analysis_limitation;
-- Q14) Product Mix Optimization:
SELECT
    p.category,
    p.product,
    SUM(s.sold_quantity) AS sales_volume,
    SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS revenue,
    SUM(s.sold_quantity * (ISNULL(gp.gross_price,0) -
                           ISNULL(mc.manufacturing_cost,0))) AS estimated_gross_profit
FROM dim_product p
LEFT JOIN fact_sales_monthly s
  ON p.product_code = s.product_code
LEFT JOIN fact_gross_price gp
  ON s.product_code = gp.product_code
 AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
LEFT JOIN fact_manufacturing_cost mc
  ON s.product_code = mc.product_code
 AND dbo.fn_GetFiscalYear(s.date) = mc.cost_year
GROUP BY p.category, p.product
ORDER BY estimated_gross_profit DESC, sales_volume DESC;
-- Q15) Customer Lifetime Value Calculation
SELECT
    c.customer_code,
    c.customer,
    c.market,
    SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS observed_gross_revenue_clv,
    COUNT(DISTINCT s.date) AS purchase_months
FROM dim_customer c
LEFT JOIN fact_sales_monthly s
  ON c.customer_code = s.customer_code
LEFT JOIN fact_gross_price gp
  ON s.product_code = gp.product_code
 AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
GROUP BY c.customer_code, c.customer, c.market
ORDER BY observed_gross_revenue_clv DESC;
-- Q16) Inventory Management Analysis
SELECT
    p.product_code,
    p.product,
    p.inventory_count,
    ISNULL(SUM(s.sold_quantity),0) AS total_sold_quantity,
    CASE
      WHEN p.inventory_count = 0 THEN NULL
      ELSE SUM(ISNULL(s.sold_quantity,0)) * 1.0 / p.inventory_count
    END AS simple_inventory_turnover_ratio,
    CASE
      WHEN ISNULL(SUM(s.sold_quantity),0) = 0 THEN 'Slow / No Movement'
      WHEN SUM(s.sold_quantity) < p.inventory_count * 0.25 THEN 'Slow Moving'
      ELSE 'Normal'
    END AS inventory_status
FROM dim_product p
LEFT JOIN fact_sales_monthly s
  ON p.product_code = s.product_code
GROUP BY p.product_code, p.product, p.inventory_count
ORDER BY simple_inventory_turnover_ratio;
-- Q17) Competitor Benchmarking:
-- The supplied schema contains no competitor sales or market-share data.
-- Therefore a true competitor benchmark cannot be calculated.
SELECT
    'Competitor benchmarking cannot be calculated from the supplied schema because no competitor table/fields are provided.' AS limitation;
-- Q18) Price Elasticity Estimation:
SELECT
    s.product_code,
    dbo.fn_GetFiscalYear(s.date) AS fiscal_year,
    s.date,
    gp.gross_price,
    SUM(s.sold_quantity) AS sold_quantity
FROM fact_sales_monthly s
JOIN fact_gross_price gp
  ON s.product_code = gp.product_code
 AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
GROUP BY s.product_code, dbo.fn_GetFiscalYear(s.date), s.date, gp.gross_price
ORDER BY s.product_code, s.date;
-- Q19) Customer Satisfaction Analysis:
-- No customer feedback/satisfaction field is supplied in the schema.
SELECT
    'Customer satisfaction analysis cannot be calculated because no feedback or satisfaction table/column is provided.' AS limitation;
-- Q20) Marketing Campaign Effectiveness:
-- No campaign spend or campaign-response fields are supplied.
SELECT
    'Marketing campaign effectiveness cannot be calculated because no campaign, spend, or campaign-response data is provided.' AS limitation;

-- TASK 5
-- ============================================================================
-- Q1) Define a user-defined function to calculate total forecasted quantity for a given product and fiscal year.
CREATE FUNCTION dbo.fn_TotalForecastedQuantity
(
    @ProductCode VARCHAR(45),
    @FiscalYear INT
)
RETURNS BIGINT
AS
BEGIN
    DECLARE @TotalForecast BIGINT;

    SELECT @TotalForecast = ISNULL(SUM(forecast_quantity),0)
    FROM fact_forecast_monthly
    WHERE product_code = @ProductCode
      AND fiscal_year = @FiscalYear;

    RETURN @TotalForecast;
END;

SELECT dbo.fn_TotalForecastedQuantity('A0118150101', 2018) AS total_forecasted_quantity;
-- Q2) Find customers who made purchases exceeding the average monthly sales quantity across all products.
WITH CustomerMonthlySales AS
(
    SELECT
        customer_code,
        date,
        SUM(sold_quantity) AS monthly_customer_quantity
    FROM fact_sales_monthly
    GROUP BY customer_code, date
),
OverallAverage AS
(
    SELECT AVG(monthly_customer_quantity * 1.0) AS avg_monthly_quantity
    FROM CustomerMonthlySales
)
SELECT
    c.customer_code,
    c.customer,
    SUM(cms.monthly_customer_quantity) AS total_quantity
FROM CustomerMonthlySales cms
JOIN dim_customer c
  ON cms.customer_code = c.customer_code
CROSS JOIN OverallAverage oa
GROUP BY c.customer_code, c.customer
HAVING SUM(cms.monthly_customer_quantity) > MAX(oa.avg_monthly_quantity)
ORDER BY total_quantity DESC;
-- Q3) Create a stored procedure to update gross price of a product for a specific fiscal year.
CREATE PROCEDURE dbo.usp_UpdateGrossPrice
    @ProductCode VARCHAR(45),
    @FiscalYear INT,
    @NewGrossPrice DECIMAL(15,4)
AS
BEGIN
    SET NOCOUNT ON;

    IF @NewGrossPrice < 0
    BEGIN
        RAISERROR('Gross price cannot be negative.',16,1);
        RETURN;
    END;

    IF EXISTS
    (
        SELECT 1
        FROM fact_gross_price
        WHERE product_code = @ProductCode
          AND fiscal_year = @FiscalYear
    )
    BEGIN
        UPDATE fact_gross_price
        SET gross_price = @NewGrossPrice
        WHERE product_code = @ProductCode
          AND fiscal_year = @FiscalYear;
    END
    ELSE
    BEGIN
        INSERT INTO fact_gross_price(product_code, fiscal_year, gross_price)
        VALUES(@ProductCode, @FiscalYear, @NewGrossPrice);
    END
END;
GO

-- Example:
-- EXEC dbo.usp_UpdateGrossPrice 'A0118150101', 2018, 16.0000;
GO


-- Q4) Create a trigger that automatically inserts a record into the audit
-- log table whenever a new entry is added to the sales table.
CREATE TRIGGER trg_Sales_AuditLog
ON fact_sales_monthly
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO audit_log
    (table_name, action_type, product_code, customer_code, sold_quantity, message)
    SELECT
        'fact_sales_monthly',
        'INSERT',
        product_code,
        customer_code,
        sold_quantity,
        'New sales record inserted.'
    FROM inserted;
END;
GO


-- Q5) Use a window function to rank products based on monthly sales quantity,
-- partitioned by fiscal year.
SELECT
    dbo.fn_GetFiscalYear(date) AS fiscal_year,
    date,
    product_code,
    SUM(sold_quantity) AS monthly_sales_quantity,
    RANK() OVER
    (
        PARTITION BY dbo.fn_GetFiscalYear(date), date
        ORDER BY SUM(sold_quantity) DESC
    ) AS product_rank
FROM fact_sales_monthly
GROUP BY dbo.fn_GetFiscalYear(date), date, product_code
ORDER BY fiscal_year, date, product_rank;
GO


-- Q6) Use STRING_AGG to concatenate names of all customers who purchased
-- a specific product within a given timeframe.
DECLARE @ProductForStringAgg VARCHAR(45) = 'A0118150101';
DECLARE @StartDate DATE = '2017-09-01';
DECLARE @EndDate DATE = '2018-08-31';

SELECT
    @ProductForStringAgg AS product_code,
    STRING_AGG(c.customer, ', ') AS customers
FROM
(
    SELECT DISTINCT customer_code
    FROM fact_sales_monthly
    WHERE product_code = @ProductForStringAgg
      AND date BETWEEN @StartDate AND @EndDate
) s
JOIN dim_customer c
  ON s.customer_code = c.customer_code;
GO


-- Q7) Develop a UDF calculating total manufacturing cost for a product
-- over a specified range of years, using a subquery.
CREATE FUNCTION dbo.fn_TotalManufacturingCost
(
    @ProductCode VARCHAR(45),
    @StartYear INT,
    @EndYear INT
)
RETURNS DECIMAL(18,4)
AS
BEGIN
    DECLARE @TotalCost DECIMAL(18,4);

    SELECT @TotalCost =
    (
        SELECT ISNULL(SUM(manufacturing_cost),0)
        FROM fact_manufacturing_cost
        WHERE product_code = @ProductCode
          AND cost_year BETWEEN @StartYear AND @EndYear
    );

    RETURN @TotalCost;
END;
GO

SELECT dbo.fn_TotalManufacturingCost('A0118150101', 2018, 2021) AS total_manufacturing_cost;
GO


-- Q8) Stored procedure to insert new sales records and trigger to ensure
-- quantity sold does not exceed available inventory.
CREATE TRIGGER trg_ValidateSalesInventory
ON fact_sales_monthly
INSTEAD OF INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS
    (
        SELECT 1
        FROM inserted i
        JOIN dim_product p
          ON i.product_code = p.product_code
        WHERE i.sold_quantity > p.inventory_count
    )
    BEGIN
        RAISERROR('Quantity sold cannot exceed available inventory.',16,1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;

    INSERT INTO fact_sales_monthly(date, product_code, customer_code, sold_quantity)
    SELECT date, product_code, customer_code, sold_quantity
    FROM inserted;
END;
GO

CREATE PROCEDURE dbo.usp_InsertSale
    @Date DATE,
    @ProductCode VARCHAR(45),
    @CustomerCode BIGINT,
    @SoldQuantity INT
AS
BEGIN
    SET NOCOUNT ON;

    IF @SoldQuantity <= 0
    BEGIN
        RAISERROR('Sold quantity must be greater than zero.',16,1);
        RETURN;
    END;

    INSERT INTO fact_sales_monthly
    (date, product_code, customer_code, sold_quantity)
    VALUES
    (@Date, @ProductCode, @CustomerCode, @SoldQuantity);
END;
GO


-- Q9) Use LAG to compare monthly sales quantity with previous month's sales.
WITH MonthlyProductSales AS
(
    SELECT
        product_code,
        date,
        SUM(sold_quantity) AS monthly_sales_quantity
    FROM fact_sales_monthly
    GROUP BY product_code, date
)
SELECT
    product_code,
    date,
    monthly_sales_quantity,
    LAG(monthly_sales_quantity) OVER
    (
        PARTITION BY product_code
        ORDER BY date
    ) AS previous_month_sales,
    monthly_sales_quantity -
        LAG(monthly_sales_quantity) OVER
        (
            PARTITION BY product_code
            ORDER BY date
        ) AS change_from_previous_month
FROM MonthlyProductSales
ORDER BY product_code, date;
GO


-- Q10) Identify top-selling products in each market using subqueries
-- and window functions.
WITH ProductMarketSales AS
(
    SELECT
        c.market,
        s.product_code,
        SUM(s.sold_quantity) AS total_sales_quantity
    FROM fact_sales_monthly s
    JOIN dim_customer c
      ON s.customer_code = c.customer_code
    GROUP BY c.market, s.product_code
),
Ranked AS
(
    SELECT *,
           DENSE_RANK() OVER
           (
               PARTITION BY market
               ORDER BY total_sales_quantity DESC
           ) AS market_rank
    FROM ProductMarketSales
)
SELECT
    market,
    product_code,
    total_sales_quantity,
    market_rank
FROM Ranked
WHERE market_rank <= 3
ORDER BY market, market_rank, product_code;
GO


-- Q11) UDF to calculate total freight cost for a product based on market
-- and fiscal year, then integrate it into a stored procedure to update
-- the overall cost.
CREATE FUNCTION dbo.fn_TotalFreightCost
(
    @ProductCode VARCHAR(45),
    @Market VARCHAR(45),
    @FiscalYear INT
)
RETURNS DECIMAL(18,4)
AS
BEGIN
    DECLARE @FreightCost DECIMAL(18,4);

    SELECT @FreightCost =
        ISNULL(SUM(s.sold_quantity * gp.gross_price * fc.freight_pct),0)
    FROM fact_sales_monthly s
    JOIN fact_gross_price gp
      ON s.product_code = gp.product_code
     AND gp.fiscal_year = @FiscalYear
    JOIN fact_freight_cost fc
      ON fc.market = @Market
     AND fc.fiscal_year = @FiscalYear
    WHERE s.product_code = @ProductCode
      AND dbo.fn_GetFiscalYear(s.date) = @FiscalYear;

    RETURN @FreightCost;
END;
GO

CREATE PROCEDURE dbo.usp_UpdateOverallCost
    @ProductCode VARCHAR(45),
    @Market VARCHAR(45),
    @FiscalYear INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        @ProductCode AS product_code,
        @Market AS market,
        @FiscalYear AS fiscal_year,
        dbo.fn_TotalManufacturingCost(@ProductCode,@FiscalYear,@FiscalYear)
            AS manufacturing_cost,
        dbo.fn_TotalFreightCost(@ProductCode,@Market,@FiscalYear)
            AS freight_cost,
        dbo.fn_TotalManufacturingCost(@ProductCode,@FiscalYear,@FiscalYear)
        + dbo.fn_TotalFreightCost(@ProductCode,@Market,@FiscalYear)
            AS overall_cost;
END;
GO


-- Q12) Trigger to automatically update inventory count in product table
-- whenever a new sale is recorded.
CREATE TRIGGER trg_UpdateInventoryAfterSale
ON fact_sales_monthly
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE p
    SET p.inventory_count = p.inventory_count - x.total_sold
    FROM dim_product p
    JOIN
    (
        SELECT product_code, SUM(sold_quantity) AS total_sold
        FROM inserted
        GROUP BY product_code
    ) x
      ON p.product_code = x.product_code;
END;
GO


-- Q13) Trigger to enforce referential integrity so only products listed
-- in product table can be inserted into sales table.
CREATE TRIGGER trg_ValidateSalesProduct
ON fact_sales_monthly
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS
    (
        SELECT 1
        FROM inserted i
        WHERE NOT EXISTS
        (
            SELECT 1
            FROM dim_product p
            WHERE p.product_code = i.product_code
        )
    )
    BEGIN
        RAISERROR('Invalid product code: product does not exist in dim_product.',16,1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;
GO


-- Q14) Stored procedure generating month-over-month sales growth for each product.
CREATE PROCEDURE dbo.usp_ProductMoMGrowth
AS
BEGIN
    SET NOCOUNT ON;

    WITH MonthlySales AS
    (
        SELECT
            product_code,
            date,
            SUM(sold_quantity) AS monthly_sales
        FROM fact_sales_monthly
        GROUP BY product_code, date
    ),
    SalesWithPrevious AS
    (
        SELECT *,
               LAG(monthly_sales) OVER
               (
                   PARTITION BY product_code
                   ORDER BY date
               ) AS previous_month_sales
        FROM MonthlySales
    )
    SELECT
        product_code,
        date,
        monthly_sales,
        previous_month_sales,
        CASE
          WHEN previous_month_sales IS NULL OR previous_month_sales = 0
            THEN NULL
          ELSE ((monthly_sales - previous_month_sales) * 100.0
                / previous_month_sales)
        END AS mom_growth_pct
    FROM SalesWithPrevious
    ORDER BY product_code, date;
END;
GO


-- Q15) UDF to calculate average discount percentage given to customers
-- for a specific product.
CREATE FUNCTION dbo.fn_AverageDiscountPercentage
(
    @ProductCode VARCHAR(45)
)
RETURNS DECIMAL(10,4)
AS
BEGIN
    DECLARE @AverageDiscount DECIMAL(10,4);

    SELECT @AverageDiscount =
        ISNULL(AVG(discounts_pct * 100.0),0)
    FROM fact_post_invoice_deductions
    WHERE product_code = @ProductCode;

    RETURN @AverageDiscount;
END;
GO

SELECT dbo.fn_AverageDiscountPercentage('A0118150101') AS average_discount_percentage;
GO


-- Q16) Identify customers with the highest total purchases in each region.
WITH CustomerRegionSales AS
(
    SELECT
        c.region,
        c.customer_code,
        c.customer,
        SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS total_purchases
    FROM dim_customer c
    JOIN fact_sales_monthly s
      ON c.customer_code = s.customer_code
    LEFT JOIN fact_gross_price gp
      ON s.product_code = gp.product_code
     AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
    GROUP BY c.region, c.customer_code, c.customer
),
RankedCustomers AS
(
    SELECT *,
           DENSE_RANK() OVER
           (
               PARTITION BY region
               ORDER BY total_purchases DESC
           ) AS region_rank
    FROM CustomerRegionSales
)
SELECT
    region,
    customer_code,
    customer,
    total_purchases
FROM RankedCustomers
WHERE region_rank = 1
ORDER BY region;
GO


-- Q17) Stored procedure to calculate total revenue generated from sales
-- for a given period.
CREATE PROCEDURE dbo.usp_TotalRevenueForPeriod
    @StartDate DATE,
    @EndDate DATE
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        @StartDate AS start_date,
        @EndDate AS end_date,
        SUM(s.sold_quantity * ISNULL(gp.gross_price,0)) AS total_gross_revenue
    FROM fact_sales_monthly s
    LEFT JOIN fact_gross_price gp
      ON s.product_code = gp.product_code
     AND dbo.fn_GetFiscalYear(s.date) = gp.fiscal_year
    WHERE s.date >= @StartDate
      AND s.date <= @EndDate;
END;
GO


-- Q18) Trigger to add a forecast record whenever a new product is added.
-- A helper UDF returns a baseline forecast quantity from existing forecast data.
CREATE FUNCTION dbo.fn_BaselineForecast
(
    @ProductCode VARCHAR(45),
    @FiscalYear INT
)
RETURNS INT
AS
BEGIN
    DECLARE @Forecast INT;

    SELECT @Forecast =
        ISNULL(ROUND(AVG(CAST(forecast_quantity AS FLOAT)),0),0)
    FROM fact_forecast_monthly
    WHERE fiscal_year = @FiscalYear;

    RETURN @Forecast;
END;
GO

CREATE TRIGGER trg_NewProductForecast
ON dim_product
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @FiscalYear INT = dbo.fn_GetFiscalYear(CAST(GETDATE() AS DATE));
    DECLARE @ForecastDate DATE =
        DATEFROMPARTS(@FiscalYear - 1, 9, 1);

    INSERT INTO fact_forecast_monthly
    (date, fiscal_year, product_code, customer_code, forecast_quantity)
    SELECT
        @ForecastDate,
        @FiscalYear,
        i.product_code,
        c.customer_code,
        dbo.fn_BaselineForecast(i.product_code, @FiscalYear)
    FROM inserted i
    CROSS JOIN dim_customer c
    WHERE NOT EXISTS
    (
        SELECT 1
        FROM fact_forecast_monthly f
        WHERE f.date = @ForecastDate
          AND f.product_code = i.product_code
          AND f.customer_code = c.customer_code
    );
END;
GO


-- Q19) Trigger to identify outliers in monthly sales using window functions.
-- Outlier table required by Task-5 Q19.
CREATE TABLE sales_outlier_log (
    outlier_id INT IDENTITY(1,1) PRIMARY KEY,
    sales_date DATE,
    product_code VARCHAR(45),
    customer_code BIGINT,
    sold_quantity INT,
    average_quantity DECIMAL(18,2),
    standard_deviation DECIMAL(18,2),
    flag VARCHAR(30),
    created_at DATETIME2 DEFAULT SYSDATETIME()
);



CREATE TRIGGER trg_FlagSalesOutliers
ON fact_sales_monthly
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH ProductStats AS
    (
        SELECT
            s.product_code,
            s.date,
            SUM(s.sold_quantity) AS monthly_quantity,
            AVG(CAST(SUM(s.sold_quantity) AS FLOAT))
                OVER (PARTITION BY s.product_code) AS avg_quantity,
            STDEV(CAST(SUM(s.sold_quantity) AS FLOAT))
                OVER (PARTITION BY s.product_code) AS std_quantity
        FROM fact_sales_monthly s
        GROUP BY s.product_code, s.date
    ),
    InsertedMonths AS
    (
        SELECT DISTINCT product_code, date
        FROM inserted
    )
    INSERT INTO sales_outlier_log
    (sales_date, product_code, sold_quantity, average_quantity,
     standard_deviation, flag)
    SELECT
        ps.date,
        ps.product_code,
        ps.monthly_quantity,
        ps.avg_quantity,
        ISNULL(ps.std_quantity,0),
        'OUTLIER'
    FROM ProductStats ps
    JOIN InsertedMonths im
      ON ps.product_code = im.product_code
     AND ps.date = im.date
    WHERE ps.std_quantity IS NOT NULL
      AND ABS(ps.monthly_quantity - ps.avg_quantity)
            > (2 * ps.std_quantity);
END;
GO


-- Q20) Retrieve products with the highest average gross price across all
-- fiscal years using a subquery and inbuilt functions.
WITH ProductAveragePrice AS
(
    SELECT
        product_code,
        AVG(gross_price) AS average_gross_price
    FROM fact_gross_price
    GROUP BY product_code
)
SELECT
    product_code,
    average_gross_price
FROM ProductAveragePrice
WHERE average_gross_price =
(
    SELECT MAX(average_gross_price)
    FROM ProductAveragePrice
)
ORDER BY product_code;
GO


-- ============================================================================
-- TASK 6
-- Analyze monthly forecast accuracy for a specific product over multiple
-- fiscal years using PIVOT. Forecast quantity and actual sold quantity are
-- presented side by side for each month.
-- ============================================================================

DECLARE @Task6ProductCode VARCHAR(45) = 'A0118150101';

WITH ForecastByMonth AS
(
    SELECT
        fiscal_year,
        MONTH(date) AS calendar_month,
        SUM(forecast_quantity) AS forecast_quantity
    FROM fact_forecast_monthly
    WHERE product_code = @Task6ProductCode
    GROUP BY fiscal_year, MONTH(date)
),
ActualByMonth AS
(
    SELECT
        dbo.fn_GetFiscalYear(date) AS fiscal_year,
        MONTH(date) AS calendar_month,
        SUM(sold_quantity) AS actual_quantity
    FROM fact_sales_monthly
    WHERE product_code = @Task6ProductCode
    GROUP BY dbo.fn_GetFiscalYear(date), MONTH(date)
),
Combined AS
(
    SELECT
        COALESCE(f.fiscal_year, a.fiscal_year) AS fiscal_year,
        COALESCE(f.calendar_month, a.calendar_month) AS calendar_month,
        ISNULL(f.forecast_quantity,0) AS forecast_quantity,
        ISNULL(a.actual_quantity,0) AS actual_quantity
    FROM ForecastByMonth f
    FULL OUTER JOIN ActualByMonth a
      ON f.fiscal_year = a.fiscal_year
     AND f.calendar_month = a.calendar_month
),
LongFormat AS
(
    SELECT fiscal_year, calendar_month, 'Forecast' AS metric, forecast_quantity AS quantity
    FROM Combined
    UNION ALL
    SELECT fiscal_year, calendar_month, 'Actual' AS metric, actual_quantity AS quantity
    FROM Combined
)
SELECT
    fiscal_year,
    calendar_month,
    ISNULL([Forecast],0) AS forecast_quantity,
    ISNULL([Actual],0) AS actual_quantity,
    CASE
      WHEN ISNULL([Forecast],0) = 0 THEN NULL
      ELSE ISNULL([Actual],0) * 100.0 / [Forecast]
    END AS forecast_accuracy_pct
FROM LongFormat
PIVOT
(
    SUM(quantity)
    FOR metric IN ([Forecast], [Actual])
) p
ORDER BY fiscal_year, calendar_month;
GO

/*
TASK 6 INTERPRETATION GUIDE
---------------------------
Forecast accuracy is calculated as:
    Actual Sold Quantity / Forecast Quantity * 100

- Around 100%: forecast closely matches actual demand.
- Below 100%: actual sales were lower than forecast (possible over-forecasting).
- Above 100%: actual sales exceeded forecast (possible under-forecasting).
- Missing forecast or sales values are retained through FULL OUTER JOIN and
  treated as zero where appropriate.
- Very high/low discrepancies can result from promotions, seasonality,
  stock-outs, new-product launches, customer behavior, or incomplete data.
*/


-- ============================================================================
-- OPTIONAL VALIDATION QUERIES
-- ============================================================================

SELECT * FROM dim_customer;
SELECT * FROM dim_product;
SELECT * FROM fact_forecast_monthly;
SELECT * FROM fact_freight_cost;
SELECT * FROM fact_gross_price;
SELECT * FROM fact_manufacturing_cost;
SELECT * FROM fact_post_invoice_deductions;
SELECT * FROM fact_pre_invoice_deductions;
SELECT * FROM fact_sales_monthly;
SELECT * FROM audit_log;
SELECT * FROM sales_outlier_log;
GO

/*
================================================================================
END OF PROJECT
================================================================================
*/
